### ISSUE TITLE
0x001 | android.view.WindowManager$BadTokenException: Unable to add window

### ISSUE THREAD

**Issue by Moosphan** [Moosphan/Android-Bug-Collections#2]
#### 错误类型：
**BadTokenException**
#### 日志信息：
完整日志信息如下：
```
Process: com.example.test, PID: 26269
    android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@da7868c is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:988)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:398)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
        at android.app.Dialog.show(Dialog.java:342)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at com.example.tuyafirstday.crash.example.UnableAddWindowCrashActivity.showDialog(UnableAddWindowCrashActivity.java:106)
        at com.example.tuyafirstday.crash.example.UnableAddWindowCrashActivity.testNormalWindowCrash(UnableAddWindowCrashActivity.java:66)
        at com.example.tuyafirstday.crash.example.UnableAddWindowCrashActivity.access$000(UnableAddWindowCrashActivity.java:29)
        at com.example.tuyafirstday.crash.example.UnableAddWindowCrashActivity$1$1.run(UnableAddWindowCrashActivity.java:47)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by Moosphan** [comment]
这类问题的原因一般是：经过异步请求返回后显示弹窗，当前 Activity 已经被销毁，从而抛出异常。如何规避 crash？有以下几种方案：

1. 如果在固定了屏幕尺寸或者设置了 configChanges 属性情况下，那么 Activity 不会在屏幕方向等配置信息变化后重建，就不会导致销毁，那么可以直接通过 Activity.isFinishing() 方法来解决。
2. 如果没有设置 configChanges 属性，我们需要额外添加 Activty.isDestroyed() 来与 Activity.isFinishing() 双重保证，因为页面配置信息变化后 Activity.isFinishing() 方法依旧返回 false，而这里 isDestroyed() 方法返回 true，额外保证程序正常运行。

代码示例：

```java
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_unable_add_window_crash);

        Button button = findViewById(R.id.crash);
        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new Handler(getMainLooper()).postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        Log.w(TAG, "----- Current Activity is finished? => before dialog showing: " + isFinishing() + " --- isDestroyed? => " + isDestroyed());
                        // 通过#isFinishing()和#isDestroyed()方法可以规避风险，因为屏幕旋转后，isDestroyed()返回true
                        if (!isFinishing() && !isDestroyed()) {
                             showDialog();
                        }
                    }
                }, 5000);
            }
        });
    
```
